backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - {
          label: 'Featured Image (appears in the index/listing page)',
          name: 'featuredimage',
          widget: image,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields: [{ label: Title, name: title, widget: string }],
            }
          - {
              label: Main Pitch description,
              name: mainpitch_description,
              widgeth: markdown,
              required: false,
            }
          - {
              label: Highlights,
              name: highlights,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: markdown },
                ],
            }
          - { label: 'Quotes title', name: quotestitle, widget: string }
          - { label: 'Quotes text', name: quotestext, widget: markdown }
          - {
              label: Quotes,
              name: quotes,
              widget: list,
              fields: [{ label: Text, name: text, widget: markdown }],
            }
          - {
              label: Awards,
              name: awards,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: text },
                ],
            }
      - file: 'src/pages/xadaptable/index.md'
        label: 'XAdaptable'
        name: 'xadaptable'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'xadaptable-page',
            }
          - { label: Image, name: image, widget: image }
          - { label: 'Title', name: 'title', widget: 'string' }

      - file: 'src/pages/test/index.md'
        name: 'test'
        label: 'Tests page'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'test-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }

      - file: 'src/pages/adaptable/index.md'
        label: 'Adaptable Page'
        name: 'adaptable'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'adaptable-page',
            }
          - { label: Image, name: image, widget: image }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Video', name: 'video', widget: 'text', required: false }
          - { label: 'Headline', name: 'headline', widget: 'markdown' }
          - {
              label: Description,
              name: description,
              widgeth: 'markdown',
              required: false,
            }
          - {
              label: 'Key features title',
              name: 'keyfeaturestitle',
              widget: 'string',
            }
          - {
              label: 'Key Features',
              name: keyfeatures,
              widget: list,
              fields:
                [
                  {
                    label: 'Feature description',
                    name: description,
                    required: false,
                    widget: text,
                  },
                  { label: 'Feature video', name: video, widget: text },
                ],
            }
          - { label: 'Call to action text', name: 'cta', widget: string }
          - { label: 'Usecases title', name: 'usecaseTitle', widget: string }
          - {
              label: 'Usecases',
              name: usecases,
              widget: list,
              fields:
                [
                  { label: 'Who', name: who, widget: text },
                  { label: 'Where', name: where, widget: text },
                  { label: 'Result', name: result, widget: text },
                  { label: 'Image', name: image, widget: image },
                ],
            }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - file: 'src/pages/grid-gurus/index.md'
        label: 'Grid Gurus'
        name: 'grid-gurus'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'grid-gurus-page',
            }
          - { label: Image, name: image, widget: image }
          - { label: 'Video', name: 'video', widget: 'text', required: false }
          - {
              label: 'Call to action 1',
              name: 'cta1',
              widget: 'string',
              required: false,
            }
          - { label: 'Headline', name: 'headline', widget: 'markdown' }
          - {
              label: 'Description',
              name: 'description',
              widget: 'markdown',
              required: false,
            }
          - {
              name: 'services',
              widget: list,
              fields: [{ label: 'service name', name: name, widget: string }],
            }
          - {
              name: 'testimonials',
              widget: list,
              fields:
                [{ label: 'testimonial text', name: text, widget: string }],
            }

          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Blog title', name: 'blogtitle', widget: 'string' }
      # - file: 'src/pages/other-data-tools-partners/index.md'
      #   label: 'Other Data Tools (Partners)'
      #   name: 'other-data-tools-partners'
      #   fields:
      #     - {
      #         label: 'Template Key',
      #         name: 'templateKey',
      #         widget: 'hidden',
      #         default: 'adaptable-page',
      #       }
      #     - { label: Image, name: image, widget: image }
      #     - { label: 'Title', name: 'title', widget: 'string' }
      #     - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      # - file: 'src/pages/contact/index.md'
      #   label: 'Contact'
      #   name: 'contact'
      #   fields:
      #     - {
      #         label: 'Template Key',
      #         name: 'templateKey',
      #         widget: 'hidden',
      #         default: 'contact-page',
      #       }
      #     - { label: 'Title', name: 'title', widget: 'string' }
      #     - { label: 'Image', name: 'image', widget: 'image' }
      #     - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/support/index.md'
        label: 'Support'
        name: 'support'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'contact-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
