import React from 'react'
import Avatar from 'avataaars'
export default [
  <Avatar
    avatarStyle="Circle"
    pieceSize={100}
    topType="LongHairMiaWallace"
    accessoriesType="Blank"
    hairColor="BrownDark"
    facialHairType="Blank"
    clotheType="BlazerShirt"
    eyeType="Default"
    eyebrowType="Default"
    mouthType="Default"
    skinColor="Light"
  />,
  <Avatar
    avatarStyle="Circle"
    pieceSize={100}
    topType="ShortHairShortFlat"
    accessoriesType="Round"
    hairColor="Brown"
    facialHairType="BeardLight"
    facialHairColor="Brown"
    clotheType="BlazerShirt"
    eyeType="Default"
    eyebrowType="Default"
    mouthType="Smile"
    skinColor="Brown"
  />,
  <Avatar
    avatarStyle="Circle"
    pieceSize={100}
    topType="LongHairStraightStrand"
    accessoriesType="Blank"
    hairColor="Brown"
    facialHairType="Blank"
    clotheType="BlazerShirt"
    eyeType="Happy"
    eyebrowType="RaisedExcited"
    mouthType="Twinkle"
    skinColor="Brown"
  />,
  <Avatar
    avatarStyle="Circle"
    pieceSize={100}
    topType="LongHairStraightStrand"
    accessoriesType="Blank"
    hairColor="Black"
    facialHairType="Blank"
    clotheType="ShirtScoopNeck"
    clotheColor="Red"
    eyeType="Default"
    eyebrowType="DefaultNatural"
    mouthType="Twinkle"
    skinColor="Pale"
  />,
  <Avatar
    avatarStyle="Circle"
    pieceSize={100}
    topType="ShortHairShortRound"
    accessoriesType="Blank"
    hairColor="BrownDark"
    facialHairType="Blank"
    clotheType="Hoodie"
    clotheColor="Heather"
    eyeType="Default"
    eyebrowType="DefaultNatural"
    mouthType="Twinkle"
    skinColor="Black"
  />
]
